<center><h1 style="padding:0px 5px 0px 5px; font-family:garamond;">MLA</h1><h2 style="padding:0px 5px 0px 5px; font-family:garamond;">“To be or not to be: that is the Question.” (Shakespeare III.1)</h2></center>
<p style="padding:0px 5px 0px 5px;font-size:20px;font-family:garamond;">All scholarly publications acknowledge that borrowed ideas and quoted words must be attributed to their original authors. However, documentation conventions vary, because different research environments and literary genres generate unique constraints, opportunities, difficulties, and obligations. MLA documentation style is widely used for humanities publications, especially for language and literature publications. Simpler than other documentation styles, MLA style features attribution within the text of an essay using brief parenthetical citations referencing an alphabetical list of “Works Cited” at the end of the essay.</p>
<p style="padding:0px 5px 0px 5px;font-size:20px;font-family:garamond;">The Modern Language Association (MLA) instructs authors how to cite primary and secondary sources including books, magazines, journals, essays, correspondence, e-books, tweets, e-journals, and websites. These citation methods are called MLA Style. MLA publishes two authoritative MLA style guides: MLA Handbook for Writers of Research Papers, and MLA Style Manual and Guide to Scholarly Publishing. Southeastern Louisiana University’s English Department has a summary of MLA principles and examples on its website, and Perdue University’s OWL (Online Writing Lab) maintains extensive examples and explanations of MLA style on its website.</p>
<p style="padding:0px 5px 0px 5px;font-size:20px;font-family:garamond;">MLA style has been widely adopted by publishers, educational institutions, and instructors for over half a century and is used by scholarly journals, newsletters, magazines, university presses, and commercial presses throughout North America and in other countries around the world— including Brazil, China, India, Japan, and Taiwan.</p>
<p style="padding:0px 5px 0px 5px;font-size:16px;font-family:garamond;">According to OWL, the generalized form of an MLA citation is:<br>
<center><p style="padding:0px 5px 0px 5px;font-size:20px;font-family:garamond;">Author. Title. Title of container (self contained if book), Other contributors (translators or editors), Version (edition), Number (vol. and/or no.), Publisher, Publication Date, Location (pages, paragraphs URL or DOI). 2nd container’s title, Other contributors, Version, Number, Publisher, Publication date, Location, Date of Access (if applicable). (OWL)</p></center></p>

<p style="padding:0px 5px 0px 5px;font-size:20px;font-family:garamond;">All MLA citations follow this form:</p>

<center><p style="padding:0px 5px 0px 5px;font-size:20px;font-family:garamond;">Works Cited</p></center>
<p style="padding:0px 5px 0px 5px;font-size:20px;font-family:garamond;">Shakespeare, William. The Tragedy of Hamlet, Prince of Denmark. Edited by Barbara A. Mowat and Paul Werstine. Folger Digital Texts.  Act III, Scene 1. www.folgerdigitaltexts.org/download/pdf/Ham.pdf. Accessed 8 April 2017.</p>

<p style="padding:0px 5px 0px 5px;font-size:20px;font-family:garamond;">Perdue Online Writing Lab (OWL). “MLA Works Cited: Other Common Sources.” www.owl.english.purdue.edu/owl/resource/747/09/. Accessed 8 April 2017.</p>
